[project]
name = "notification-bot"
version = "0.1.0"
description = "Devman Notification Bot"
requires-python = "==3.13.*"
dependencies = [
    "argparse>=1.4.0",
    "httpx>=0.28.1",
    "pydantic>=2.11.10",
    "python-dotenv>=1.1.1",
    "python-telegram-bot>=22.5",
]
